Development gridproxy examples
crystaluniverse/crystallib pull request #266
Opened 2023-10-16 12:35 UTC by 0oM4R

- update some imports and filters
- I added examples for 
     - Nodes
        - get all nodes
        - get nodes with some prop of NodeFilter
        - get node iteration 
        - get node statistics by id
        - get node by available resources 
        
     - gateway :
        -  get all gateway nodes 
        - get gateway with some prop of GatewayFilter
        - get gateway by node id
        - get gateway iteration 
        
     - Farm :
        -  get all farms 
        - get farm with some  prop FarmFilter
        - get farm iteration 
        
     - twin :
        -  get all twins 
        - get twin with some  prop TwinFilter
        - get twin iteration 
        
     - stats :
        - get grid stats for online nodes and all nodes
        
     - contracts: 
          - get all contracts
          - get contracts with some prop of ContractsFilter
          - get contracts iteration 
  

### related issue 
- #242

2023-10-16 13:15 UTC, Omarabdul3ziz approved these changes
looks good to me

2023-10-16 13:56 UTC, ashraffouda requested changes

2023-10-16 13:56 UTC, ashraffouda commented on examples/threefold/gridproxy/easy/contract.v
> +
can we split both examples in two functions and call them in main? just to be clear that those are two separate examples

2023-10-18 07:41 UTC, ashraffouda approved these changes

2023-10-18 07:42 UTC, merged