fix/check tfgrid client
crystaluniverse/crystallib pull request #448
Opened 2024-06-06 17:06 UTC by renauter

## Related issues:

- #438

2024-06-27 13:20 UTC, MarioBassem requested changes

2024-06-27 13:20 UTC, MarioBassem commented on crystallib/threefold/grid/factory.v
> +		mut cl := get(instance,
the client is initiated and not used. what is the purpose of the `tfgridclient.define` action?

2024-06-27 13:20 UTC, MarioBassem commented on crystallib/threefold/grid/factory.v
> +	envs := ['main', 'qa', 'test', 'dev']
v-analyzer says `duplicate of a const name 'threefold.grid.envs'`, which is indeed defined in deployer.v

2024-06-27 13:22 UTC, MarioBassem reviewed
there is one issue with current code i believe is a result of an update in V. 
there is multiple places where we try to access private fields of structs, i believe this was permitted before, but now it's now. so currently, with the latest version of V, none of the examples work.
the issue is, for example, with the `griddriver.Client` struct: https://github.com/freeflowuniverse/crystallib/blob/development_tfgrid_fixes/crystallib/threefold/griddriver/client.v#L3
and the access happens in multiple places like: https://github.com/freeflowuniverse/crystallib/blob/development_tfgrid_fixes/crystallib/threefold/grid/deployer.v#L59

2024-06-27 14:12 UTC, renauter commented
> there is one issue with current code i believe is a result of an update in V. there is multiple places where we try to access private fields of structs, i believe this was permitted before, but now it's now.

I see. It seems to be due to V update indeed, not allowing such access anymore. Before it was just warning, now it is error. I think I fixed it here https://github.com/freeflowuniverse/crystallib/pull/448/commits/b31d3ef14aa823bb546e7ed1ed980e984eb7eb02 but reverted the commit here https://github.com/freeflowuniverse/crystallib/pull/448/commits/4eb48fab1e6368fd074fa1273c5433de1b79f224 after. I ll restore and it should be fine.

2024-07-01 10:03 UTC, renauter commented on crystallib/threefold/grid/factory.v
> +	envs := ['main', 'qa', 'test', 'dev']
Good catch.
I ll replace with:

~~~vlang
	cfg.network = myui.ask_dropdown(
		question: 'choose environment'
		items: grid.envs.values()
	)!
~~~

2024-07-01 10:56 UTC, renauter commented on crystallib/threefold/grid/factory.v
> +		mut cl := get(instance,
I see.
To be honest I don't get what this function `heroplay()` is for.
I updated the code and made it similar to what I found in `dagu`.

I also see 2 versions of this function for other clients with different arguments:
~~~vlang
pub fn heroplay(mut plbook playbook.PlayBook)
~~~
and
~~~vlang
pub fn heroplay(args play.PLayBookAddArgs)
~~~

Not sure which one is more up to date and should be considered as reference ?

2024-07-01 12:16 UTC, MarioBassem approved these changes

2024-07-03 13:59 UTC, merged