fix: updates in ourdb:
crystaluniverse/crystallib pull request #491
Opened 2024-10-31 15:28 UTC by MarioBassem

- add file switching functionality in ourdb
- fix get history functionality

2024-11-09 01:27 UTC, despiegk requested changes

2024-11-09 01:27 UTC, despiegk commented on crystallib/core/ourdb/backend.v
> +// // delete zeros out the record at specified location
why did we remove this?
we need to delete the data which is no longer needed

2024-11-09 01:27 UTC, despiegk commented on crystallib/core/ourdb/db.v
> +	// db.delete_(x, location)!
yes

2024-11-10 08:42 UTC, MarioBassem commented on crystallib/core/ourdb/backend.v
> +// // delete zeros out the record at specified location
i get that we need to delete data, but isn't it sufficient to delete the location of the record from the lookup table?

2024-12-15 11:08 UTC, merged